'use strict';

// tests for test-graphql
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect  = mochaPlugin.chai.expect;
let wrapped   = mochaPlugin.getWrapper('test-graphql', '/src/handler/graphql/index.js', 'handler');

describe('test-graphql', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
