version: 0.1

phases:
  install:
    commands:
      #- apt-get update
# -y - need for after answer for questions
      #- apt-get -y install npm
      - node --version
      - npm --version
      - npm install
      – npm install -g serverless
  build:
    commands:
      - npm --version
      - node --version
  post_build:
    commands:
      – sls deploy

artifacts:
  files:
    – serverless.yml
    – publish.zip
discard-paths: yes