version: 0.1

phases:
  install:
    commands:
#      - apt-get update
###      -y - need for after answer for questions
#      - apt-get -y install npm
      - npm install -g serverless
      - npm install
#  build:
#    commands:
#      - npm --version
#      - node --version
  post_build:
    commands:
      - sls deploy
### user $env from options of build
#      – serverless deploy –stage $env –region us-west-2 –verbose

artifacts:
  files:
    – serverless.yml
    – package.json
    – buildspec.yml
discard-paths: yes