version: 0.1

phases:
  install:
    commands:
      - apt-get update
# -y - need for after answer for questions
      - apt-get -y install npm
  build:
    commands:
      – npm install -g serverless
      - npm install
  post_build:
    commands:
      – sls deploy

artifacts:
  files:
    – serverless.yml
    – publish.zip
discard-paths: yes