version: 0.1

phases:
  install:
    commands:
      - apt update
      - apt install npm
#      – npm install -g serverless
  build:
    commands:
      - npm install
  post_build:
    commands:
      – sls deploy

artifacts:
  files:
    – serverless.yml
    – publish.zip
discard-paths: yes