version: 0.1

phases:
  install:
    commands:
      – apt-get -y update
      – npm install -g serverless
      - npm install
  build:
    commands:
  post_build:
    commands:
      – sls deploy

artifacts:
files:
  – serverless.yml
  – publish.zip
discard-paths: yes